'use client';
import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { apiRequest } from '@/lib/api';
import { ErrorPanel, LoadingPanel, PageHeading } from './ui';
import { Documents, OperationForm, OperationsTable, PrivateFile, display, getValue, type FieldSpec, type RecordData } from './operations-ui';
import { AnalyticsPanel, SystemPanel } from './system-panels';
const reason: FieldSpec = { name: 'reason', label: 'Motivo de la decisión', type: 'textarea', min: 10, max: 1000 };
const reviewFields: FieldSpec[] = [{ name: 'status', label: 'Decisión', type: 'select', options: ['APPROVED', 'REJECTED', 'SUSPENDED'] }, reason];
const legalTypes = ['GENERAL_TERMS', 'PRIVACY_POLICY', 'SHIPPING_TERMS', 'PROHIBITED_ITEMS_POLICY', 'DRIVER_TERMS', 'MERCHANT_TERMS'];
const legalFields: FieldSpec[] = [{ name: 'type', label: 'Tipo de documento', type: 'select', options: legalTypes }, { name: 'title', label: 'Título', min: 4, max: 150 }, { name: 'version', label: 'Versión', max: 40 }, { name: 'mandatory', label: 'Aceptación obligatoria', type: 'checkbox' }, { name: 'content', label: 'Texto completo revisado', type: 'textarea', min: 50, max: 100000 }];
const policyFields: FieldSpec[] = [{ name: 'category', label: 'Código de categoría', min: 2, max: 80 }, { name: 'status', label: 'Clasificación', type: 'select', options: ['ALLOWED', 'RESTRICTED', 'PROHIBITED'] }, { name: 'isActive', label: 'Categoría activa', type: 'checkbox' }, { name: 'description', label: 'Descripción de la política', type: 'textarea', min: 10, max: 2000 }];
const logisticFields: FieldSpec[] = [
  ...([['maxWeightKg', 'Peso máximo (kg)', 0.01, 1000], ['maxLengthCm', 'Largo máximo (cm)', 1, 500], ['maxWidthCm', 'Ancho máximo (cm)', 1, 500], ['maxHeightCm', 'Alto máximo (cm)', 1, 500], ['maxDistanceKm', 'Distancia máxima tarifaria (km)', 0.1, 200], ['baseFee', 'Tarifa base (S/)', 0, 1000], ['perKmFee', 'Precio por km (S/)', 0, 100], ['perKgFee', 'Precio por kg (S/)', 0, 100], ['perLiterFee', 'Precio por litro (S/)', 0, 100], ['serviceFee', 'Tarifa de servicio (S/)', 0, 1000], ['fragileFee', 'Recargo por fragilidad (S/)', 0, 1000]] as const).map(([name, label, min, max]) => ({ name, label, type: 'number' as const, min, max })),
  { name: 'cashAllowed', label: 'Permitir efectivo', type: 'checkbox' }, { name: 'isActive', label: 'Habilitar vehículo y tarifas', type: 'checkbox' },
];
const definitions: Record<string, { title: string; description: string; endpoint: string; columns: Array<[string, string]> }> = {
  repartidores: { title: 'Repartidores', description: 'Verifica documentos y registra una decisión. La aprobación no conecta al repartidor automáticamente.', endpoint: '/drivers/admin/drivers', columns: [['Documento', 'documentNumber'], ['Vehículo', 'vehicleType'], ['Solicitud', 'applicationStatus'], ['Disponibilidad', 'status']] },
  comercios: { title: 'Comercios', description: 'Solicitudes, documentación y estado de los establecimientos afiliados.', endpoint: '/orders/admin/merchants', columns: [['Establecimiento', 'name'], ['RUC', 'ruc'], ['Solicitud', 'applicationStatus'], ['Dirección', 'address']] },
  pedidos: { title: 'Pedidos', description: 'Pedidos reales con sus subpedidos, importes y trazabilidad. La cancelación inicia conciliación si corresponde.', endpoint: '/orders/orders', columns: [['Pedido', 'orderNumber'], ['Tipo', 'type'], ['Estado', 'status'], ['Total (S/)', 'total']] },
  envios: { title: 'Envíos personales', description: 'Revisa artículos restringidos. Una categoría prohibida nunca puede aprobarse.', endpoint: '/orders/admin/shipments', columns: [['Envío', 'orderNumber'], ['Estado', 'status'], ['Categoría', 'shipment.packageCategory'], ['Revisión', 'shipment.reviewStatus']] },
  pagos: { title: 'Pagos', description: 'El efectivo se confirma al entregar. Mercado Pago se concilia por webhook firmado. Solo los comprobantes manuales admiten revisión aquí.', endpoint: '/orders/admin/payments', columns: [['Pedido', 'order.orderNumber'], ['Método', 'method'], ['Estado', 'status'], ['Importe (S/)', 'amount']] },
  reembolsos: { title: 'Reembolsos', description: 'Aprobar no significa transferir dinero. Registra evidencia para conciliar una devolución manual; Mercado Pago requiere confirmación del proveedor.', endpoint: '/orders/admin/refunds', columns: [['Pedido', 'order.orderNumber'], ['Estado', 'status'], ['Importe (S/)', 'amount'], ['Motivo', 'reason']] },
  soporte: { title: 'Soporte', description: 'Consultas recibidas y respuestas visibles para sus titulares.', endpoint: '/users/admin/support?type=SUPPORT', columns: [['Asunto', 'subject'], ['Estado', 'status'], ['Usuario', 'userId'], ['Descripción', 'description']] },
  incidencias: { title: 'Incidencias', description: 'Investiga problemas de entrega y deja una respuesta trazable.', endpoint: '/users/admin/support?type=INCIDENT', columns: [['Asunto', 'subject'], ['Estado', 'status'], ['Pedido', 'orderId'], ['Descripción', 'description']] },
  privacidad: { title: 'Privacidad', description: 'Gestiona acceso, rectificación, eliminación y oposición. Resolver una solicitud exige efectuar el tratamiento correspondiente y justificarlo.', endpoint: '/users/admin/privacy', columns: [['Tipo', 'type'], ['Estado', 'status'], ['Usuario', 'userId'], ['Solicitud', 'description']] },
  legal: { title: 'Documentos legales', description: 'Edita borradores, publica versiones revisadas y conserva el historial. Los documentos publicados son inmutables.', endpoint: '/users/admin/legal', columns: [['Documento', 'title'], ['Tipo', 'type'], ['Versión', 'version'], ['Estado', 'status']] },
  politicas: { title: 'Políticas de artículos', description: 'Clasificación versionada: permitido, restringido o prohibido. Cada modificación invalida cotizaciones anteriores.', endpoint: '/orders/admin/item-policies', columns: [['Categoría', 'category'], ['Clasificación', 'status'], ['Versión', 'version'], ['Activa', 'isActive']] },
  logistica: { title: 'Logística y tarifas', description: 'Define capacidad y precios antes de habilitar un vehículo. La distancia tarifaria actual es en línea recta, no una ruta vial.', endpoint: '/orders/admin/logistics', columns: [['Vehículo', 'vehicleType'], ['Peso máximo (kg)', 'maxWeightKg'], ['Base (S/)', 'baseFee'], ['Habilitado', 'isActive']] },
  roles: { title: 'Roles y permisos', description: 'Permisos aplicados por el servidor. Los cambios de rol revocan las sesiones de la cuenta afectada.', endpoint: '/users/admin/roles', columns: [['Rol', 'role'], ['Permisos', 'permissions']] },
  configuracion: { title: 'Configuración de pagos', description: 'Habilita únicamente métodos configurados. Los secretos del proveedor se gestionan fuera del navegador mediante variables de entorno.', endpoint: '/orders/admin/payment-configuration', columns: [['Método', 'method'], ['Habilitado', 'enabled'], ['Cuenta', 'accountLabel'], ['Instrucciones', 'instructions']] },
  notificaciones: { title: 'Notificaciones', description: 'Estado registrado de envíos in-app, correo y push; un fallo no se presenta como entrega.', endpoint: '/notifications/notifications/admin/all', columns: [['Título', 'title'], ['Canal', 'channel'], ['Estado', 'status'], ['Fecha', 'createdAt']] },
  promociones: { title: 'Promociones', description: 'Cupones con vigencia y límites validados en servidor.', endpoint: '/orders/promotions', columns: [['Código', 'code'], ['Tipo', 'type'], ['Valor', 'value'], ['Activa', 'isActive']] },
};
const promotionFields: FieldSpec[] = [{ name: 'code', label: 'Código', min: 3, max: 30 }, { name: 'type', label: 'Tipo', type: 'select', options: ['PERCENTAGE', 'FIXED', 'FREE_DELIVERY'] }, { name: 'value', label: 'Valor del beneficio', type: 'number', min: 0.01 }, { name: 'minimumAmount', label: 'Compra mínima (S/)', type: 'number', min: 0 }, { name: 'maximumDiscount', label: 'Descuento máximo (S/)', type: 'number', min: 0.01, optional: true }, { name: 'usageLimit', label: 'Máximo de usos', type: 'number', min: 1, optional: true }, { name: 'startsAt', label: 'Inicio', type: 'datetime-local' }, { name: 'expiresAt', label: 'Vencimiento', type: 'datetime-local' }];
function RecordDetails({ row, section }: { row: RecordData; section: string }) {
  const id = String(row.id);
  if (['repartidores', 'comercios'].includes(section)) return <><Documents value={row.documents ?? row.applicationDocuments} /><p className="text-sm text-slate-600">Última revisión: {display(row.reviewReason)}</p><OperationForm fields={reviewFields} endpoint={'/api/backend/' + (section === 'repartidores' ? 'drivers/admin/drivers/' : 'orders/admin/merchants/') + id + '/review'} label="Registrar revisión" /></>;
  if (section === 'pagos') return <><p className="text-sm">Operación: {display(row.operationCode)} · Referencia del proveedor: {display(row.providerPaymentId)} · Motivo: {display(row.reviewReason)}</p>{typeof row.evidenceFileId === 'string' && <PrivateFile id={row.evidenceFileId} label="Ver comprobante" />}{row.provider === 'MANUAL' && row.status === 'PAYMENT_PENDING_VERIFICATION' && <OperationForm endpoint={'/api/backend/orders/payments/' + id + '/review'} method="POST" fields={[{ name: 'decision', label: 'Resultado de la verificación', type: 'select', options: ['APROBAR', 'RECHAZAR'] }, reason]} transform={({ decision, ...values }) => ({ ...values, approved: decision === 'APROBAR' })} label="Registrar verificación" />}</>;
  if (section === 'reembolsos') return <><p className="text-sm">Referencia conciliada: {display(row.providerReference)}</p>{['REQUESTED', 'APPROVED'].includes(String(row.status)) && <OperationForm endpoint={'/api/backend/orders/admin/refunds/' + id} fields={[{ name: 'status', label: 'Decisión', type: 'select', options: row.status === 'APPROVED' ? ['REJECTED', 'COMPLETED'] : ['APPROVED', 'REJECTED'] }, reason, { name: 'providerReference', label: 'Referencia externa de devolución', optional: true }, { name: 'evidenceFileId', label: 'Comprobante de devolución', type: 'file', purpose: 'PAYMENT_EVIDENCE', optional: true }]} label="Registrar decisión" />}</>;
  if (['soporte', 'incidencias', 'privacidad'].includes(section)) return <><p className="whitespace-pre-wrap text-sm">Respuesta actual: {display(row.response ?? row.resolution)}</p><OperationForm endpoint={'/api/backend/users/admin/' + (section === 'privacidad' ? 'privacy/' : 'support/') + id} fields={[{ name: 'status', label: 'Estado', type: 'select', options: ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'REJECTED'] }, { name: 'response', label: 'Respuesta para el titular', type: 'textarea', min: 5, max: 3000 }]} initial={{ status: row.status, response: row.response ?? row.resolution }} label="Responder y actualizar" /></>;
  if (section === 'legal') return <><div className="max-h-96 overflow-auto whitespace-pre-wrap rounded-xl border border-slate-200 bg-white p-5 text-sm leading-7">{display(row.content)}</div>{row.status === 'DRAFT' ? <><OperationForm fields={legalFields} initial={row} endpoint={'/api/backend/users/admin/legal/' + id} label="Guardar borrador" /><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="mb-4 text-sm text-amber-900">Publicar exige revisión jurídica previa. Una vez publicada, esta versión no se puede editar.</p><OperationForm fields={[{ name: 'effectiveAt', label: 'Entrada en vigor', type: 'datetime-local' }]} endpoint={'/api/backend/users/admin/legal/' + id + '/publish'} method="POST" label="Publicar versión revisada" /></div></> : <p className="text-sm text-slate-500">Publicada: {display(row.publishedAt)} · Vigente desde: {display(row.effectiveAt)}</p>}</>;
  if (section === 'politicas') return <><OperationForm fields={policyFields} initial={row} endpoint={'/api/backend/orders/admin/item-policies/' + id} label="Guardar nueva revisión" /><details><summary className="cursor-pointer text-sm font-bold">Historial de versiones</summary><pre className="mt-3 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(row.revisions, null, 2)}</pre></details></>;
  if (section === 'logistica') return <OperationForm fields={logisticFields} initial={row} endpoint={'/api/backend/orders/admin/logistics/' + row.vehicleType} label="Guardar capacidad y tarifa" />;
  if (section === 'configuracion') return <OperationForm fields={[{ name: 'enabled', label: 'Habilitar método', type: 'checkbox' }, { name: 'accountLabel', label: 'Titular / cuenta de destino', optional: true }, { name: 'instructions', label: 'Instrucciones al cliente', type: 'textarea', min: 10, max: 2000, optional: true }, { name: 'qrFileId', label: 'QR de la cuenta', type: 'file', purpose: 'PAYMENT_QR', optional: true }]} initial={row} endpoint={'/api/backend/orders/admin/payment-configuration/' + row.method} />;
  if (section === 'promociones') return <OperationForm endpoint={'/api/backend/orders/promotions/' + id} initial={row} fields={[{ name: 'isActive', label: 'Campaña activa', type: 'checkbox' }, { name: 'usageLimit', label: 'Límite de usos', type: 'number', min: 1, optional: true }]} />;
  if (section === 'envios') return <><div className="grid gap-3 text-sm md:grid-cols-2">{[['Recogida', 'pickupAddress'], ['Destino', 'dropoffAddress'], ['Contenido', 'contentDescription'], ['Peso (kg)', 'weightKg'], ['Vehículo', 'vehicleType'], ['Motivo de revisión', 'reviewReason']].map(([label, key]) => <p key={key}><strong>{label}:</strong> {display(getValue(row, 'shipment.' + key))}</p>)}</div>{typeof getValue(row, 'shipment.packageImageUrl') === 'string' && <PrivateFile id={String(getValue(row, 'shipment.packageImageUrl'))} label="Foto del paquete" />}{['pickupEvidenceFileId', 'deliveryEvidenceFileId'].map(key => typeof getValue(row, 'shipment.' + key) === 'string' && <PrivateFile key={key} id={String(getValue(row, 'shipment.' + key))} label={key === 'pickupEvidenceFileId' ? 'Evidencia de recogida' : 'Evidencia de entrega'} />)}{row.status === 'REQUIRES_REVIEW' && <OperationForm fields={[{ ...reviewFields[0]!, options: ['APPROVED', 'REJECTED', 'INVESTIGATION'] }, reason]} endpoint={'/api/backend/orders/admin/shipments/' + id + '/review'} label="Registrar revisión del envío" />}</>;
  if (section === 'pedidos') return <><div className="grid gap-3 md:grid-cols-2">{Array.isArray(row.subOrders) && row.subOrders.map((sub, index) => <div key={index} className="rounded-xl border border-slate-200 bg-white p-4 text-sm"><strong>{display(getValue(sub, 'merchant.name'))}</strong><p>{display(getValue(sub, 'status'))}</p>{Array.isArray(getValue(sub, 'items')) && (getValue(sub, 'items') as unknown[]).map((item, i) => <p key={i}>{display(getValue(item, 'quantity'))} × {display(getValue(item, 'productName'))}</p>)}</div>)}</div><p className="text-sm">Pago: {display(row.paymentStatus)} · Repartidor asignado: {display(row.assignedDriverId)}</p><details><summary className="text-sm font-bold">Ver trazabilidad</summary><pre className="overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(row.statusHistory, null, 2)}</pre></details>{!['CANCELLED', 'DELIVERED'].includes(String(row.status)) && <OperationForm endpoint={'/api/backend/orders/orders/' + id + '/status'} fields={[{ name: 'confirm', label: 'Confirma la cancelación', type: 'select', options: ['CANCELAR PEDIDO'] }]} transform={() => ({ status: 'CANCELLED' })} label="Cancelar pedido y abrir conciliación si corresponde" />}</>;
  if (section === 'notificaciones') return <p className="whitespace-pre-wrap text-sm text-slate-600">{display(row.message)} · Usuario: {display(row.userId)}</p>;
  return null;
}
function RecordsPanel({ section }: { section: string }) {
  const definition = definitions[section]!;
  const [creating, setCreating] = useState(false);
  const query = useQuery({ queryKey: ['admin-section', section], queryFn: () => apiRequest<RecordData[]>('/api/backend' + definition.endpoint), refetchInterval: ['pedidos', 'envios', 'pagos', 'notificaciones'].includes(section) ? 10000 : false });
  const createFields = section === 'legal' ? legalFields : section === 'politicas' ? policyFields : section === 'promociones' ? promotionFields : undefined;
  return <><PageHeading eyebrow="Administración" title={definition.title} description={definition.description} action={createFields && <button className="rounded-xl bg-[#1e194b] px-5 py-3 text-sm font-bold text-white" onClick={() => setCreating(value => !value)}>{creating ? 'Cerrar formulario' : 'Crear nuevo'}</button>} />
    {creating && createFields && <section className="mb-6 rounded-2xl border border-slate-200 bg-white p-6"><OperationForm key={section} endpoint={'/api/backend' + definition.endpoint} method="POST" fields={createFields} initial={{ mandatory: true, isActive: true }} label={section === 'legal' ? 'Crear borrador' : 'Crear registro'} onSuccess={() => setCreating(false)} /></section>}
    {query.isLoading ? <LoadingPanel /> : query.isError ? <ErrorPanel message={query.error.message} /> : <OperationsTable rows={query.data ?? []} columns={definition.columns} details={section === 'roles' ? undefined : row => <RecordDetails key={String(row.id ?? row.method ?? row.vehicleType) + ':' + String(row.updatedAt ?? row.version ?? row.status ?? '')} row={row} section={section} />} />}
    {section === 'roles' && <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="mb-4 text-lg font-bold">Cambiar rol de una cuenta</h2><RoleForm /></div>}
  </>;
}
function RoleForm() {
  const [id, setId] = useState('');
  return <><label className="mb-4 block text-xs font-bold text-slate-600">ID de usuario<input value={id} onChange={event => setId(event.target.value)} placeholder="UUID de la cuenta" className="mt-2 block h-11 w-full rounded-xl border border-slate-200 px-3" /></label>{/^[a-f0-9-]{36}$/i.test(id) && <OperationForm key={id} endpoint={'/api/backend/users/admin/users/' + id + '/role'} fields={[{ name: 'role', label: 'Nuevo rol', type: 'select', options: ['CUSTOMER', 'DRIVER', 'MERCHANT', 'ADMIN'] }, reason]} label="Cambiar rol y revocar sesiones" />}</>;
}
function AuditPanel() {
  const query = useQuery({ queryKey: ['combined-audit'], queryFn: async () => {
    const results = await Promise.all(['/users/users/audit', '/orders/admin/audit', '/drivers/admin/drivers/audit'].map(async path => (await apiRequest<RecordData[]>('/api/backend' + path)).map(row => ({ ...row, source: path.split('/')[1] }))));
    return results.flat().sort((a, b) => display(getValue(b, 'createdAt')).localeCompare(display(getValue(a, 'createdAt'))));
  } });
  return <><PageHeading eyebrow="Trazabilidad" title="Auditoría" description="Acciones de identidad, operaciones y repartidores. Los códigos de verificación y secretos no se incluyen." />{query.isLoading ? <LoadingPanel /> : query.isError ? <ErrorPanel message={query.error.message} /> : <OperationsTable rows={query.data ?? []} columns={[['Origen', 'source'], ['Acción', 'action'], ['Entidad', 'entity'], ['Fecha', 'createdAt']]} details={row => <pre className="overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(row.metadata ?? {}, null, 2)}</pre>} />}</>;
}
export function AdminOperations({ section }: { section: string }) {
  if (section === 'analitica') return <AnalyticsPanel />;
  if (section === 'monitoreo') return <SystemPanel />;
  if (section === 'auditoria') return <AuditPanel />;
  if (definitions[section]) return <RecordsPanel key={section} section={section} />;
  return <ErrorPanel message="Esta sección no existe." />;
}
