'use client';
import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Activity, CheckCircle2, CircleDollarSign, Clock3, Package, ShoppingBag } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { apiRequest } from '@/lib/api';
import { ErrorPanel, KpiCard, LoadingPanel, PageHeading, StatusBadge } from './ui';
export type ServiceState = { service: string; status: string; reachable: boolean; dependencies?: Record<string, string>; optional?: Record<string, string> };
export type Analytics = { orders: number; delivered: number; cancelled: number; shipments: number; revenue: number; averageDeliveryMinutes: number | null; hours: Array<{ hour: string; orders: number; delivered: number }> };
export function DemandChart({ hours }: { hours: Analytics['hours'] }) { return <div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={hours}><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="#e9eef3" /><XAxis dataKey="hour" tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis allowDecimals={false} tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip /><Area dataKey="orders" name="Pedidos" stroke="#1e194b" fill="#e8e5fa" strokeWidth={2} /></AreaChart></ResponsiveContainer></div>; }
export function SystemPanel() {
  const query = useQuery({ queryKey: ['system-readiness'], queryFn: () => apiRequest<ServiceState[]>('/api/backend/orders/admin/system'), refetchInterval: 10000 });
  return <><PageHeading eyebrow="Observabilidad" title="Estado de los servicios" description="Preparación real de las dependencias, consultada cada diez segundos. Configurado no significa verificado." />
    {query.isLoading ? <LoadingPanel /> : query.isError ? <ErrorPanel message={query.error.message} /> : <div className="grid gap-5 md:grid-cols-2">{query.data?.map(service => <article key={service.service} className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><Activity className={service.status === 'ready' ? 'text-emerald-600' : 'text-red-600'} /><StatusBadge value={service.status} /></div><h2 className="my-5 text-lg font-extrabold text-slate-800">{service.service}</h2><dl className="space-y-3">{Object.entries(service.dependencies ?? {}).map(([key, value]) => <div key={key} className="flex justify-between gap-4 text-sm"><dt className="text-slate-500">{key}</dt><dd className={value === 'ok' ? 'font-bold text-emerald-700' : 'font-bold text-red-700'}>{value}</dd></div>)}</dl>{Object.entries(service.optional ?? {}).map(([key, value]) => <p key={key} className="mt-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-900">{key}: {value}</p>)}{!service.reachable && <p className="text-sm text-red-700">No se pudo contactar con el servicio.</p>}</article>)}</div>}
  </>;
}
export function AnalyticsPanel() {
  const [period, setPeriod] = useState('day');
  const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const params = new URLSearchParams({ period, ...(from ? { from } : {}), ...(to ? { to } : {}) }).toString();
  const query = useQuery({ queryKey: ['admin-analytics', params], queryFn: () => apiRequest<Analytics>('/api/backend/orders/admin/analytics?' + params) });
  function download() { if (!query.data) return; const csv = 'hora,pedidos,entregados\r\n' + query.data.hours.map(value => [value.hour, value.orders, value.delivered].join(',')).join('\r\n'); const url = URL.createObjectURL(new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'demanda-delivereats.csv'; anchor.click(); URL.revokeObjectURL(url); }
  return <><PageHeading eyebrow="Datos de operación" title="Analítica" description="Volumen de pedidos y entregas registrado en el periodo. Zona horaria: America/Lima." />
    <div className="mb-6 flex flex-wrap items-end gap-4"><label className="text-xs font-bold text-slate-500">Periodo<select className="mt-2 block h-11 rounded-xl border border-slate-200 bg-white px-3" value={period} onChange={event => { setPeriod(event.target.value); setFrom(''); setTo(''); }}><option value="day">Hoy</option><option value="week">Últimos 7 días</option><option value="month">Últimos 30 días</option></select></label><label className="text-xs font-bold text-slate-500">Desde<input className="mt-2 block h-11 rounded-xl border border-slate-200 px-3" type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label className="text-xs font-bold text-slate-500">Hasta<input className="mt-2 block h-11 rounded-xl border border-slate-200 px-3" type="date" value={to} onChange={event => setTo(event.target.value)} /></label><button disabled={!query.data} onClick={download} className="h-11 rounded-xl bg-[#1e194b] px-4 text-sm font-bold text-white disabled:opacity-40">Exportar demanda CSV</button></div>
    {query.isLoading ? <LoadingPanel /> : query.isError ? <ErrorPanel message={query.error.message} /> : query.data && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[
      ['Pedidos', String(query.data.orders), 'Todos los estados', ShoppingBag], ['Entregados', String(query.data.delivered), 'Entrega completada', CheckCircle2], ['Volumen entregado', 'S/ ' + query.data.revenue.toFixed(2), 'No representa utilidad neta', CircleDollarSign], ['Envíos personales', String(query.data.shipments), 'Del total de pedidos', Package], ['Cancelados', String(query.data.cancelled), 'Durante el periodo', Activity], ['Tiempo de entrega', query.data.averageDeliveryMinutes == null ? '—' : query.data.averageDeliveryMinutes + ' min', 'Desde creación hasta entrega', Clock3],
    ].map(([label, value, hint, Icon]) => <KpiCard key={String(label)} label={String(label)} value={String(value)} hint={String(hint)} icon={Icon as typeof Activity} />)}</div><section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="mb-5 text-lg font-bold text-slate-800">Distribución de pedidos por hora del día</h2><DemandChart hours={query.data.hours} /></section></>}
  </>;
}

